### ISSUE TITLE
What is ReMobidyc ? Why not tell us in the announcements ?

### ISSUE THREAD

**Issue by Mr-Dispatch** [ReMobidyc/ReMobidyc#252]
I heard about something getting released on PharoWeekly.
It was named ReMobidyc, and I apperently cared.
```
Dear all,

I’m delighted to announce that the first major version of re:mobidyc
(codename Thonon) has been released.
https://github.com/ReMobidyc/ReMobidyc

Re:mobidyc Thonon is based on Pharo 11 and its pre-built packages on
major platforms (m1/m2 mac, intel mac, windows and linux) are
available at the release page below.
https://github.com/ReMobidyc/ReMobidyc/releases/tag/Thonon

Best Regards,
```

So info, such brave.

Following the repo link, I soon gained insight into why I should care, but for whatever sake, people, try to make release announcements a bit more descriptive ;-)

**Comment by tomooda** [comment]
Thank you for your feedback. 👍  I'll try to provide more info next time! :-)
